const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const ICONS={compass:'<circle cx="12" cy="12" r="9"/><path d="m16 8-3 5-5 3 3-5z"/>',user:'<circle cx="12" cy="8" r="4"/><path d="M4 22v-3a8 8 0 0 1 16 0v3"/>',spark:'<path d="m12 3 2.5 6.5L21 12l-6.5 2.5L12 21l-2.5-6.5L3 12l6.5-2.5Z"/>',slides:'<rect x="3" y="3" width="18" height="13" rx="2"/><path d="M12 16v5m-4 0h8M8 8h8m-8 4h5"/>',arrow:'<path d="M4 12h16m-6-6 6 6-6 6"/>',search:'<circle cx="10" cy="10" r="6"/><path d="m15 15 5 5"/>',check:'<path d="m5 12 4 4L19 6"/>',close:'<path d="m6 6 12 12M18 6 6 18"/>',shield:'<path d="m12 3 8 3v6c0 4-8 9-8 9s-8-5-8-9V6Z"/><path d="m8 11 3 3 5-5"/>',chat:'<path d="M21 11a8 8 0 0 1-8 8H8l-5 3V11a9 9 0 0 1 18 0Z"/><path d="M7 10h10M7 14h6"/>',sun:'<circle cx="12" cy="12" r="4"/><path d="M12 2v2m0 16v2M2 12h2m16 0h2M5 5l1 1m12 12 1 1M5 19l1-1M18 6l1-1"/>',globe:'<circle cx="12" cy="12" r="9"/><ellipse cx="12" cy="12" rx="4" ry="9"/><path d="M3 12h18"/>',edit:'<path d="m15 4 5 5M4 20l5-1L21 7l-5-5L4 14Z"/>',book:'<path d="M12 5C8 2 4 3 2 4v15c4-2 7-1 10 1 3-2 6-3 10-1V4c-3-1-6-2-10 1v15"/>',heart:'<path d="M20 5c-3-3-7-1-8 2-1-3-5-5-8-2-5 5 2 11 8 16 6-5 13-11 8-16Z"/>',print:'<path d="M6 8V3h12v5M6 17H3V9h18v8h-3M6 14h12v7H6Z"/>',back:'<path d="M20 12H4m6-6-6 6 6 6"/>'};
const icon=(name,cls='')=>`<svg class="icon ${cls}" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${ICONS[name]||ICONS.spark}</svg>`;
let state={profile:structuredClone(DEFAULT_PROFILE),answers:[null,null,null,null,null],finished:false,pal:'hana',view:'discover'};
let storageOk=true;
try{const saved=JSON.parse(localStorage.getItem('friendmatch-v1'));if(saved&&typeof saved==='object'&&saved.profile&&typeof saved.profile.name==='string'&&Array.isArray(saved.profile.traits)&&Array.isArray(saved.profile.interests)&&saved.profile.ideal?.length===5&&saved.profile.avoid?.length===2){state.profile={...DEFAULT_PROFILE,...saved.profile};if(Array.isArray(saved.answers)&&saved.answers.length===5&&saved.answers.every(x=>x===null||Number.isInteger(x)&&x>=0&&x<=2))state.answers=saved.answers;state.finished=!!saved.finished&&state.answers.every(Number.isInteger);if(PALS.some(p=>p.id===saved.pal))state.pal=saved.pal;}}catch{storageOk=false;}
let filter='All interests',query='',step=0,slide=0,toastTimer;
const pal=()=>PALS.find(p=>p.id===state.pal)||PALS[0];
const initials=name=>name.trim().split(/\s+/).slice(0,2).map(s=>s[0]).join('').toUpperCase()||'ME';
const avatar=(p,size='')=>`<span class="avatar ${esc(p.color||'blue')} ${size}">${esc(p.initials||initials(p.name))}</span>`;
const tags=(items,cls='')=>items.map(x=>`<span class="chip ${cls}">${esc(x)}</span>`).join('');
function toast(msg){clearTimeout(toastTimer);$('#toast').textContent=msg;$('#toast').classList.add('visible');toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),3800);}
function persist(){try{localStorage.setItem('friendmatch-v1',JSON.stringify({profile:state.profile,answers:state.answers,finished:state.finished,pal:state.pal}));storageOk=true;}catch{storageOk=false;toast('This browser could not save your project. Keep this tab open.');}}
function nav(view){if(!['discover','profile','test','result','project'].includes(view))view='discover';state.view=view;location.hash=view;render();window.scrollTo({top:0,behavior:'instant'});}
function render(){
 const pages=[['discover','compass','Discover friends'],['profile','user','My character'],['test','spark','Compatibility test'],['project','slides','Class presentation']];
 $('#navigation').innerHTML=pages.map(([id,ic,label])=>`<a href="#${id}" class="nav-item ${(state.view===id||state.view==='result'&&id==='test')?'active':''}" ${state.view===id?'aria-current="page"':''}>${icon(ic)}<span>${label}</span>${id==='project'?'<span class="nav-number">5</span>':''}</a>`).join('');
 $('#breadcrumb').textContent=pages.find(x=>x[0]===state.view)?.[2]||'Your friendship match';$('#header-avatar').textContent=initials(state.profile.name);
 $('#main').innerHTML=({discover:discoverView,profile:profileView,test:testView,result:resultView,project:projectView}[state.view])();
 bindView();
}
function discoverView(){return `<div class="page-heading"><div><span class="eyebrow">A WORLD OF POSSIBILITIES</span><h1>Find your kind of friend<span class="blue">.</span></h1><p>Start with a shared interest. Discover what makes you click.</p></div><span class="hello-sticker">Say hello<br><span>to someone new ✦</span></span></div>
 <div class="discover-layout"><section class="discovery"><div class="discovery-controls"><label class="search-box">${icon('search')}<input id="search" type="search" placeholder="Search a name or country" value="${esc(query)}" aria-label="Search fictional friends by name or country"></label><span class="small-muted">${PALS.length} fictional profiles</span></div><div class="filter-row" role="group" aria-label="Filter by shared interest">${['All interests',...INTERESTS].map(x=>`<button class="filter ${filter===x?'selected':''}" data-filter="${x}" aria-pressed="${filter===x}">${x}</button>`).join('')}</div><div class="section-line"><h2>People you might click with</h2><span id="result-count"></span></div><div class="pal-grid" id="pal-grid">${cardsHTML()}</div></section>
 <aside class="right-column"><section class="your-card"><div class="card-label">YOUR CHARACTER<button class="icon-button" data-nav="profile" aria-label="Edit character">${icon('edit')}</button></div><div class="your-card-person">${avatar(state.profile,'medium')}<div><h3>${esc(state.profile.name)}, ${esc(state.profile.age)}</h3><span>${esc(state.profile.country)}</span></div></div><p class="your-bio">${esc(state.profile.enjoys)}</p><div class="chips">${tags(state.profile.interests)}</div><button class="outline-button full" data-nav="profile">Shape your character ${icon('arrow')}</button></section>
 <section class="project-card"><span class="card-label">YOUR FRIENDSHIP PROJECT</span><h3>A little curiosity.<br>A better connection.</h3><ol class="project-steps"><li><span class="step-dot done">${icon('check')}</span><div>Create your character<small>Personality, strengths & interests</small></div></li><li><span class="step-dot done">${icon('check')}</span><div>Imagine your ideal friend<small>Qualities that matter to you</small></div></li><li><span class="step-dot ${state.finished?'done':''}">${state.finished?icon('check'):'3'}</span><div>Try the 5-question test<small>Explore your compatibility</small></div></li><li><span class="step-dot ${state.finished?'done':''}">${state.finished?icon('check'):'4'}</span><div>Explain your match<small>Five categories, 50 points</small></div></li></ol><button class="blue-link" data-nav="${state.finished?'result':'test'}">${state.finished?'See your friendship score':'Find your match'} ${icon('arrow')}</button></section>
 <div class="little-note">${icon('shield')}<p>A space for practice.<br><span>Fictional friends. Real English skills.</span></p></div></aside></div>`;}
function filteredPals(){return [...PALS].filter(p=>(filter==='All interests'||p.interests.includes(filter))&&(`${p.name} ${p.country} ${p.interests.join(' ')}`.toLowerCase().includes(query.toLowerCase()))).sort((a,b)=>state.finished?calculateMatch(state.profile,b,state.answers).total-calculateMatch(state.profile,a,state.answers).total:b.interests.filter(i=>state.profile.interests.includes(i)).length-a.interests.filter(i=>state.profile.interests.includes(i)).length);}
function cardsHTML(){const list=filteredPals();if(!list.length)return `<div class="empty-state">${icon('search')}<h3>No friends found here yet</h3><p>Try another name or choose a different interest.</p><button class="outline-button" data-action="clear-filter">Clear filters</button></div>`;return list.map(p=>{const common=p.interests.filter(i=>state.profile.interests.includes(i));return `<article class="pal-card"><div class="pal-top ${p.color}"><span class="country-label">${icon('globe')} ${esc(p.country)}</span><span class="country-code">${p.flag}</span></div><div class="pal-body"><div class="pal-name-row">${avatar(p,'large')}<span class="match-label">${state.finished?`${calculateMatch(state.profile,p,state.answers).total}/50 match`:common.length?`${common.length} shared interests`:'Something new'}</span></div><button class="name-button" data-detail="${p.id}"><h3>${p.name}<span>, ${p.age}</span></h3>${icon('arrow')}</button><span class="pal-role">${p.role}</span><p class="pal-bio">${p.bio}</p><div class="chips trait-chips">${tags(p.traits.slice(0,3))}</div><div class="interest-tags">${p.interests.map(i=>`<span class="${common.includes(i)?'shared':''}">${interestIcon(i)} ${i}</span>`).join('')}</div><button class="primary-button full" data-match="${p.id}">${state.finished?'See your match':'Find our connection'} ${icon('arrow')}</button></div></article>`}).join('');}
function interestIcon(i){return {Art:'✎',Music:'♫',Reading:'▤',Gaming:'♧',Sport:'⚑',Nature:'❋',Science:'✧',Cooking:'◉'}[i]||'✦';}
function profileView(){const p=state.profile;return `<div class="page-heading"><div><span class="eyebrow">STAGES 01 & 02</span><h1>Your character, your story<span class="blue">.</span></h1><p>Invent a teenager and imagine the friend they would connect with.</p></div><span class="stage-badge">Fictional profile</span></div><form id="profile-form"><div class="form-layout"><section class="panel"><div class="panel-heading"><span class="number-label">01</span><div><h2>Meet your character</h2><p>Use English for your B1 class project.</p></div></div><div class="form-row"><label>Name<input required maxlength="30" name="name" value="${esc(p.name)}"></label><label>Age<input required name="age" type="number" min="13" max="19" value="${esc(p.age)}"></label></div><label>Country<input required name="country" maxlength="45" value="${esc(p.country)}"></label><fieldset><legend>Personality <small>Choose 5–6 adjectives</small></legend><div class="choice-chips">${TRAITS.map(t=>`<label><input type="checkbox" name="traits" value="${t}" ${p.traits.includes(t)?'checked':''}><span>${t}</span></label>`).join('')}</div></fieldset><fieldset><legend>Hobbies & interests <small>Choose 2–4</small></legend><div class="choice-chips">${INTERESTS.map(t=>`<label><input type="checkbox" name="interests" value="${t}" ${p.interests.includes(t)?'checked':''}><span>${interestIcon(t)} ${t}</span></label>`).join('')}</div></fieldset>${textArea('strengths','Strengths',p.strengths)}${textArea('weaknesses','Weaknesses',p.weaknesses)}${textArea('enjoys','Things they enjoy doing',p.enjoys,'Try: enjoy drawing, love meeting, don’t mind helping.')}${textArea('dislikes','Things they dislike doing',p.dislikes,'Try: dislike waiting, avoid arguing, prefer doing.')}</section>
 <section class="panel"><div class="panel-heading"><span class="number-label">02</span><div><h2>Their ideal best friend</h2><p>Explain your choices, not just the qualities.</p></div></div><h3 class="form-subtitle">5 qualities that matter</h3>${p.ideal.map((q,i)=>`<div class="quality-row"><label>Quality ${i+1}<select name="quality-${i}">${TRAITS.filter(t=>!['impatient','disorganized','insecure'].includes(t)).map(t=>`<option ${q.quality===t?'selected':''}>${t}</option>`).join('')}</select></label><label>Why this matters<textarea name="reason-${i}" required maxlength="200" rows="2">${esc(q.reason)}</textarea></label></div>`).join('')}<h3 class="form-subtitle">2 qualities to avoid</h3>${p.avoid.map((q,i)=>`<div class="quality-row"><label>Quality ${i+1}<select name="avoid-${i}">${['dishonest','insensitive','unfriendly','unkind','unreliable','impatient','disorganized'].map(t=>`<option ${q.quality===t?'selected':''}>${t}</option>`).join('')}</select></label><label>Why this is a problem<textarea name="avoid-reason-${i}" required maxlength="200" rows="2">${esc(q.reason)}</textarea></label></div>`).join('')}${textArea('activities','Activities they could enjoy together',p.activities)}<p class="inline-note">Your selected hobbies are the interests you hope to share.</p></section></div><div class="save-bar"><span id="form-error" role="alert">Changes are saved only on this device.</span><button class="primary-button" type="submit">Save my character ${icon('check')}</button></div></form>`;}
function textArea(name,label,value,hint=''){return `<label>${label}<textarea name="${name}" required rows="3" maxlength="500">${esc(value)}</textarea>${hint?`<small class="input-help">${hint}</small>`:''}</label>`;}
function testView(){if(state.finished)return `<div class="page-heading"><div><span class="eyebrow">STAGE 03</span><h1>You’ve made a connection<span class="blue">.</span></h1><p>Your answers are ready. Compare another friend or explore your result.</p></div></div><section class="panel completed-test">${avatar(pal(),'xl')}<h2>${esc(state.profile.name)} + ${pal().name}</h2><p>Five questions. Five ways to understand each other.</p><div class="button-row"><button class="primary-button" data-nav="result">See the ${calculateMatch(state.profile,pal(),state.answers).total}/50 result ${icon('arrow')}</button><button class="outline-button" data-action="retake">Edit my answers</button><button class="text-button" data-nav="discover">Choose another friend</button></div></section>`;
 const q=QUESTIONS[step];return `<div class="page-heading"><div><span class="eyebrow">STAGE 03 · FRIENDSHIP COMPATIBILITY TEST</span><h1>What makes you click<span class="blue">?</span></h1><p>Answer as ${esc(state.profile.name)}, your fictional character.</p></div></div><div class="quiz-layout"><section class="quiz-card"><div class="quiz-top"><span class="pill">${icon(q.icon)} ${q.category}</span><span>Question ${step+1} <span class="muted">of 5</span></span></div><div class="quiz-progress" aria-label="Question ${step+1} of 5">${QUESTIONS.map((_,i)=>`<span class="${i<=step?'filled':''}"></span>`).join('')}</div><h2>${q.title}</h2><fieldset class="answers"><legend class="sr-only">Choose your response</legend>${q.options.map((o,i)=>`<label class="answer-option ${state.answers[step]===i?'chosen':''}"><input type="radio" name="answer" value="${i}" ${state.answers[step]===i?'checked':''}><span class="option-letter">${String.fromCharCode(65+i)}</span><span>${o}</span><span class="answer-check">${icon('check')}</span></label>`).join('')}</fieldset><p class="quiz-tip">${icon('spark')} ${q.tip}</p><div class="quiz-buttons"><button class="text-button" data-action="previous-question" ${step===0?'disabled':''}>${icon('back')} Back</button><button class="primary-button" data-action="next-question" ${state.answers[step]===null?'disabled':''}>${step===4?'Reveal our match':'Next question'} ${icon('arrow')}</button></div></section><aside class="quiz-aside"><span class="eyebrow">YOUR POSSIBLE FRIEND</span>${avatar(pal(),'xl')}<h2>${pal().name}, ${pal().age}</h2><p>${pal().country} · ${pal().role}</p><div class="chips">${tags(pal().interests)}</div><blockquote>“${pal().bio}”</blockquote><button class="blue-link" data-nav="discover">Choose another friend</button><div class="mini-callout">The score is a classroom model, not a scientific measure of friendship.</div></aside></div>`;}
function explanation(p,r){const common=r.common.length?r.common.join(', '):'trying unfamiliar activities';return `I would give this friendship ${r.total}/50 because ${esc(state.profile.name)} and ${p.name} ${r.common.length?`share an interest in ${common}`:'could learn about each other’s different interests'}. ${r.qualities.length?`${p.name} is ${r.qualities.join(', ')}, which matches important qualities in the ideal friend.`:'They bring different qualities to the friendship.'} ${r.scores[2]>=9?'Both characters choose to respect private information.':'They need to discuss privacy and how to earn each other’s trust.'} However, ${challenge(p,r)}`;}
function challenge(p,r){if(r.scores[2]<9)return 'reading someone’s private notes could damage trust, so they should agree to respect privacy.';if(r.scores[3]<9)return 'they may explain misunderstandings at different speeds, so they should check how the other person feels.';if(r.scores[4]<10)return 'they may prefer different rainy-day activities, so taking turns choosing would help.';if(state.profile.traits.includes('impatient'))return `${esc(state.profile.name)} can be impatient, so both friends should allow time for calm decisions.`;return 'even a strong match needs time, honest conversations and respect for differences.';}
function scoreDetails(p,r){return [
 `4 base points + ${r.qualities.length} matching ideal ${r.qualities.length===1?'quality':'qualities'} + ${state.answers[0]===p.answers[0]?2:state.answers[0]===2?0:1} response points; maximum 10.`,
 `2 base points + 2 per shared interest (${r.common.length}) + ${state.answers[1]===p.answers[1]?2:0} club-choice points; maximum 10.`,
 'The lower privacy score of both responses: returning it closed = 10, keeping it safe and asking = 9, reading a page = 2.',
 'The lower communication score of both responses: explaining kindly = 10, clarifying later = 7, leaving them to guess = 3.',
 `Same activity choice = 10; different choices = 7. ${state.answers[4]===p.answers[4]?'You chose the same activity.':'Taking turns can help you enjoy both ideas.'}`
 ];}
function resultView(){if(!state.finished)return `<div class="page-heading"><div><h1>A friendship worth exploring.</h1><p>Answer five questions to see your match.</p></div></div><button class="primary-button" data-nav="test">Start the test ${icon('arrow')}</button>`;const p=pal(),r=calculateMatch(state.profile,p,state.answers),details=scoreDetails(p,r);return `<div class="page-heading"><div><span class="eyebrow">STAGE 04 · YOUR FRIENDSHIP SCORE</span><h1>${r.total>=40?'A promising connection':'A friendship to explore'}<span class="blue">.</span></h1><p>A little shared ground, a little room to grow.</p></div><button class="outline-button" data-nav="discover">Compare friends ${icon('compass')}</button></div><div class="result-layout"><section class="score-hero"><div class="pair-avatars">${avatar(state.profile,'large')}<span class="pair-link">${icon('heart')}</span>${avatar(p,'large')}</div><h2>${esc(state.profile.name)} + ${p.name}</h2><div class="score-circle" style="--score:${r.total*2}%"><span><strong>${r.total}</strong><small>out of 50</small></span></div><span class="score-caption">${r.total>=40?'Lots of common ground':r.total>=30?'Different in interesting ways':'Plenty to talk about'}</span><p>Based on your project choices.<br>Real friendship grows over time.</p><button class="primary-button full" data-nav="project">Present this friendship ${icon('slides')}</button></section><section class="panel score-panel"><h2>Five ways you connect</h2>${r.scores.map((s,i)=>`<div class="score-row"><div>${icon(QUESTIONS[i].icon)}<span>${CATEGORIES[i]}</span><strong>${s}<span> /10</span></strong></div><div class="bar"><span style="width:${s*10}%"></span></div></div>`).join('')}<details class="scoring-details"><summary>How are the scores calculated?</summary><p>A simple, transparent classroom model. It is not a psychological test.</p>${details.map((d,i)=>`<p><strong>${CATEGORIES[i]}:</strong> ${d}</p>`).join('')}</details></section></div><div class="result-bottom"><section class="panel"><span class="eyebrow">EXPLAIN YOUR RESULT</span><p class="result-explanation">${explanation(p,r)}</p><div class="chips">${tags(r.common.map(x=>`Shared: ${x}`))}</div></section><section class="conversation-card"><span class="eyebrow">A CONVERSATION STARTER</span><h3>“${p.icebreaker}”</h3><p>Practise asking and answering this with a classmate.</p><button class="text-button" data-action="retake">Review my answers ${icon('arrow')}</button></section></div>`;}
function languageCheck(){const p=state.profile;const text=[p.traits.join(' '),p.strengths,p.weaknesses,p.enjoys,p.dislikes,...p.ideal.flatMap(x=>[x.quality,x.reason]),...p.avoid.flatMap(x=>[x.quality,x.reason]),p.activities].join(' ').toLowerCase();const adjs=[...new Set([...TRAITS,'dishonest','insensitive','unfriendly','unkind','unreliable'])].filter(a=>new RegExp('\\b'+a+'\\b').test(text));const pref=adjs.filter(a=>/^(un|in|dis|im)/.test(a));const ing=/\b(enjoy|enjoys|love|loves|avoid|avoids|prefer|prefers|mind)\s+\w+ing\b/i.test(text);return {adjs,pref,ing};}
function slideHTML(i){const p=state.profile,f=pal(),r=state.finished?calculateMatch(p,f,state.answers):null;const header=(num,k,title)=>`<div class="slide-kicker"><span>FRIEND MATCH</span><span>${k} · ${num}/05</span></div><h2>${title}</h2>`;
 if(i===0)return `${header('01','STAGE 1','Meet '+esc(p.name)+'.')}<div class="slide-columns"><div><div class="slide-person">${avatar(p,'large')}<div><h3>${esc(p.name)}, ${esc(p.age)}</h3><p>${esc(p.country)} · fictional teenager</p></div></div><div class="chips">${tags(p.traits)}</div><h4>Hobbies & interests</h4><p>${p.interests.map(esc).join(' · ')}</p><h4>Enjoys & dislikes</h4><p>${esc(p.enjoys)}</p><p>${esc(p.dislikes)}</p></div><div><div class="slide-box"><h4>Strengths</h4><p>${esc(p.strengths)}</p></div><div class="slide-box pale-yellow"><h4>Room to grow</h4><p>${esc(p.weaknesses)}</p></div><p class="slide-quote">“A good friendship leaves room for both people to grow.”</p></div></div>`;
 if(i===1)return `${header('02','STAGE 2','What makes an ideal friend?')}<div class="slide-columns"><div class="ideal-list">${p.ideal.map(q=>`<div><span>${icon('check')}</span><p><strong>${esc(q.quality)}</strong>${esc(q.reason)}</p></div>`).join('')}</div><div><div class="slide-box pale-yellow"><h4>Qualities to avoid</h4>${p.avoid.map(q=>`<p><strong>${esc(q.quality)}:</strong> ${esc(q.reason)}</p>`).join('')}</div><h4>Interests to share</h4><p>${p.interests.map(esc).join(', ')}</p><h4>Time together</h4><p>${esc(p.activities)}</p></div></div>`;
 if(i===2)return `${header('03','STAGE 3','Five questions. A better connection.')}<div class="slide-questions">${QUESTIONS.map((q,n)=>`<div><span class="q-number">${n+1}</span><div><h4>${q.title}</h4><p>${q.options.map((o,j)=>`<span class="${state.answers[n]===j?'selected-response':''}">${String.fromCharCode(65+j)}. ${o}</span>`).join(' ')}</p></div></div>`).join('')}</div>`;
 if(i===3)return `${header('04','STAGE 4',r?`${esc(p.name)} + ${f.name}: ${r.total}/50`:'Our final friendship match')}<div class="slide-columns"><div>${r?r.scores.map((s,n)=>`<div class="presentation-score"><span>${CATEGORIES[n]}</span><strong>${s}/10</strong></div>`).join(''):'<p>Complete the test to calculate your five scores.</p>'}<div class="presentation-total">TOTAL <strong>${r?r.total:'—'}/50</strong></div></div><div><h4>Why this result?</h4><p>${r?explanation(f,r):'The score and explanation appear here after you answer the five questions.'}</p><div class="mini-callout">A classroom scoring model, not a scientific prediction.</div></div></div>`;
 const l=languageCheck();return `${header('05','TEAM & LANGUAGE','Better together.')}<div class="slide-columns"><div><h4>Our team</h4>${ROLES.map((role,n)=>`<div class="team-line"><strong>${esc(p.team[n]||'Add presenter name')}</strong><span>${role}</span></div>`).join('')}<p class="small-muted">For three students, one person can combine two roles.</p><h4>Our closing thought</h4><p>We enjoy learning about each other. We don’t mind helping our friends, and we avoid arguing without listening.</p></div><div><h4>Language in our project</h4><div class="language-stat">${l.adjs.length>=8?'✓':'○'} <strong>${l.adjs.length} personality adjectives</strong><small>${l.adjs.map(esc).join(', ')}</small></div><div class="language-stat">${l.pref.length>=3?'✓':'○'} <strong>${l.pref.length} adjectives with prefixes</strong><small>${l.pref.map(esc).join(', ')}${l.pref.length<3?' · Add one more to your character.':''}</small></div><div class="language-stat">✓ <strong>Verb + -ing</strong><small>enjoy learning · don’t mind helping · avoid arguing</small></div><p class="small-muted">Assessment: content, language, creativity, presentation and teamwork — 5 points each.</p></div></div>`;
}
function projectView(){return `<div class="page-heading"><div><span class="eyebrow">DESIGN THE PERFECT FRIEND</span><h1>Your class presentation<span class="blue">.</span></h1><p>Five slides for your Grade 10 English project. Use ← and → to move between slides.</p></div><button class="outline-button" data-action="print">${icon('print')} Print / save PDF</button></div>${!state.finished?'<div class="notice">Complete the compatibility test to fill in slide 4. <button class="blue-link" data-nav="test">Take the test →</button></div>':''}<div class="presentation-shell"><div class="slide-controls"><div class="slide-tabs" aria-label="Presentation slides">${['Character','Ideal friend','The test','Our score','Team & language'].map((t,i)=>`<button data-slide="${i}" class="${slide===i?'active':''}" aria-label="Slide ${i+1}: ${t}" aria-current="${slide===i?'step':'false'}"><span>${i+1}</span><span>${t}</span></button>`).join('')}</div></div><section class="presentation-slide" aria-label="Slide ${slide+1} of 5">${slideHTML(slide)}</section><div class="presentation-nav"><button class="text-button" data-action="previous-slide" ${slide===0?'disabled':''}>${icon('back')} Previous</button><span>${slide+1} / 5</span><button class="text-button" data-action="next-slide" ${slide===4?'disabled':''}>Next ${icon('arrow')}</button></div></div><div class="presentation-support"><section class="panel"><h2>Give everyone a part</h2><p class="muted">Add your group’s first names before presenting. Use 3–4 students.</p><div class="team-inputs">${ROLES.map((r,i)=>`<label>${r}<input maxlength="40" data-team="${i}" value="${esc(state.profile.team[i]||'')}" placeholder="Presenter’s first name"></label>`).join('')}</div></section><section class="panel"><h2>Make the project your own</h2><p>Discuss the choices together. Add your own details to the character and explain why each quality matters.</p><p>Practise presenting in English. Each person should explain their part in their own words.</p><button class="blue-link" data-nav="profile">Edit our character ${icon('edit')}</button></section></div><div id="print-slides">${[0,1,2,3,4].map(i=>`<section class="print-slide">${slideHTML(i)}</section>`).join('')}</div>`;}
function bindView(){
 if(state.view==='discover'){$('#result-count').textContent=`${filteredPals().length} friends`;$('#search').addEventListener('input',e=>{query=e.target.value;$('#pal-grid').innerHTML=cardsHTML();$('#result-count').textContent=`${filteredPals().length} friends`;});}
 if(state.view==='profile')$('#profile-form').addEventListener('submit',saveProfile);
 if(state.view==='test'&&!state.finished)document.querySelectorAll('input[name="answer"]').forEach(x=>x.addEventListener('change',e=>{state.answers[step]=Number(e.target.value);persist();document.querySelectorAll('.answer-option').forEach((o,i)=>o.classList.toggle('chosen',i===state.answers[step]));$('[data-action="next-question"]').disabled=false;}));
 if(state.view==='project')document.querySelectorAll('[data-team]').forEach(el=>el.addEventListener('change',e=>{state.profile.team[Number(el.dataset.team)]=e.target.value.trim();persist();$('.presentation-slide').innerHTML=slideHTML(slide);$('#print-slides').innerHTML=[0,1,2,3,4].map(i=>`<section class="print-slide">${slideHTML(i)}</section>`).join('');}));
}
function saveProfile(e){e.preventDefault();const fd=new FormData(e.target),traits=fd.getAll('traits'),interests=fd.getAll('interests'),error=$('#form-error');if(traits.length<5||traits.length>6){error.textContent='Please choose 5–6 personality adjectives.';error.classList.add('error');toast(error.textContent);return;}if(interests.length<2||interests.length>4){error.textContent='Please choose 2–4 interests.';error.classList.add('error');toast(error.textContent);return;}const ideal=Array.from({length:5},(_,i)=>({quality:fd.get('quality-'+i),reason:fd.get('reason-'+i).trim()}));const avoid=Array.from({length:2},(_,i)=>({quality:fd.get('avoid-'+i),reason:fd.get('avoid-reason-'+i).trim()}));if(new Set(ideal.map(x=>x.quality)).size!==5||new Set(avoid.map(x=>x.quality)).size!==2){error.textContent='Choose five different ideal qualities and two different qualities to avoid.';error.classList.add('error');toast(error.textContent);return;}const strings=['name','country','strengths','weaknesses','enjoys','dislikes','activities'];if(strings.some(k=>!fd.get(k).trim())||[...ideal,...avoid].some(x=>!x.reason)){error.textContent='Please complete each field with words, not just spaces.';error.classList.add('error');return;}state.profile={...state.profile,...Object.fromEntries(strings.map(k=>[k,fd.get(k).trim()])),age:Number(fd.get('age')),traits,interests,ideal,avoid};state.profile.initials=initials(state.profile.name);persist();if(storageOk)toast('Character saved. Your matches and slides are updated.');nav('discover');}
function showModal(html){$('#modal-content').innerHTML=html;$('#modal').showModal();}
function showDetails(id){const p=PALS.find(x=>x.id===id);if(!p)return;showModal(`<button class="modal-close icon-button" data-action="close-modal" aria-label="Close profile">${icon('close')}</button><div class="detail-header">${avatar(p,'xl')}<span class="eyebrow">FICTIONAL FRIEND</span><h2 id="modal-title">${p.name}, ${p.age}</h2><p>${p.country} · ${p.role}</p></div><div class="chips">${tags(p.traits)}</div><p>${p.bio}</p><div class="detail-columns"><div><h4>Strengths</h4><p>${p.strengths}</p></div><div><h4>Weaknesses</h4><p>${p.weaknesses}</p></div></div><h4>Enjoys & dislikes</h4><p>${p.enjoys}</p><p>${p.dislikes}</p><div class="chips">${tags(p.interests)}</div><button class="primary-button full" data-match="${id}">Explore our match ${icon('arrow')}</button>`);}
function selectMatch(id){if(!PALS.some(x=>x.id===id))throw new Error('Unknown fictional friend.');state.pal=id;persist();if($('#modal').open)$('#modal').close();step=state.answers.findIndex(x=>x===null);if(step<0)step=0;nav(state.finished?'result':'test');return {friend:pal().name,view:state.view};}
function help(){showModal(`<button class="modal-close icon-button" data-action="close-modal" aria-label="Yopish">${icon('close')}</button><span class="eyebrow">QISQA YO‘RIQNOMA</span><h2 id="modal-title">Friend Match qanday ishlaydi?</h2><ol class="help-list"><li><strong>My character:</strong> xayoliy o‘smirning ismi, yoshi, 5–6 xarakter sifati, kuchli va zaif tomonlarini yozing. Ideal do‘stning 5 ta sifatini sabablar bilan belgilang.</li><li><strong>Discover friends:</strong> qiziqishlar bo‘yicha namuna do‘stni tanlang. “Find our connection” tugmasini bosing.</li><li><strong>Compatibility test:</strong> qahramoningiz nomidan 5 ta savolga javob bering.</li><li><strong>Natija:</strong> xarakter, umumiy qiziqishlar, ishonch, muloqot va birga maroqli vaqt o‘tkazish — har biri 10 ball, jami 50 ball.</li><li><strong>Class presentation:</strong> 5 ta slaydni ko‘rsating, guruh a’zolari ismlarini kiriting. “Print / save PDF” orqali saqlashingiz mumkin.</li></ol><div class="mini-callout">Bu PDF topshirig‘i uchun o‘quv namuna ilovasi. Barcha profillar xayoliy; haqiqiy odamlar bilan yozishma yo‘q. Loyiha faqat shu brauzerda saqlanadi.</div><p>Inglizcha til talablari: 8+ xarakter sifati, kamida 3 ta un-, in-/im-, dis- prefiksli sifat va fe’l + -ing shakllari.</p>`);}
document.addEventListener('click',e=>{const n=e.target.closest('[data-nav]');if(n){nav(n.dataset.nav);return;}const f=e.target.closest('[data-filter]');if(f){filter=f.dataset.filter;render();return;}const d=e.target.closest('[data-detail]');if(d){showDetails(d.dataset.detail);return;}const m=e.target.closest('[data-match]');if(m){selectMatch(m.dataset.match);return;}const s=e.target.closest('[data-slide]');if(s){slide=Number(s.dataset.slide);render();return;}const a=e.target.closest('[data-action]')?.dataset.action;if(!a)return;
 if(a==='close-modal')$('#modal').close();if(a==='clear-filter'){filter='All interests';query='';render();}if(a==='previous-question'&&step>0){step--;render();}if(a==='next-question'&&state.answers[step]!==null){if(step<4){step++;render();}else{state.finished=true;persist();nav('result');}}if(a==='retake'){state.finished=false;step=0;persist();nav('test');}if(a==='previous-slide'&&slide>0){slide--;render();}if(a==='next-slide'&&slide<4){slide++;render();}if(a==='print')window.print();
});
$('#help-button').addEventListener('click',help);
$('#modal').addEventListener('click',e=>{if(e.target===$('#modal')){const r=$('#modal').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)$('#modal').close();}});
window.addEventListener('hashchange',()=>{const view=location.hash.slice(1);if(view!==state.view)nav(view);});
document.addEventListener('keydown',e=>{if(state.view==='project'&&!['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName)&&!$('#modal').open){if(e.key==='ArrowRight'&&slide<4){slide++;render();}if(e.key==='ArrowLeft'&&slide>0){slide--;render();}}});
nav(location.hash.slice(1)||'discover');
const context=document.modelContext;
if(context?.registerTool){const lifecycle=new AbortController();window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});const registry=[
 {name:'list_fictional_friends',title:'List fictional friends',description:'Read the six classroom profiles and their shared interests with the current character.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute(input){if(!input||typeof input!=='object'||Object.keys(input).length)throw new Error('Pass an empty object.');return {character:state.profile.name,friends:PALS.map(p=>({id:p.id,name:p.name,interests:p.interests,shared:state.profile.interests.filter(x=>p.interests.includes(x))}))};}},
 {name:'start_friendship_comparison',title:'Choose a fictional friend',description:'Select a fictional friend and open the five-question test, or show the result if it is already complete. This does not send messages.',inputSchema:{type:'object',properties:{friendId:{type:'string',enum:PALS.map(p=>p.id)}},required:['friendId'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!input||typeof input!=='object'||Object.keys(input).some(k=>k!=='friendId')||typeof input.friendId!=='string')throw new Error('Provide a valid friendId.');return selectMatch(input.friendId);}}
 ];for(const tool of registry){try{Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}}}
